### ISSUE TITLE
Race in proxy events

### ISSUE THREAD

**Issue by krockot** [darinf/ports#5] opened 2015-12-28 15:15 UTC
I've observed this but haven't had time to look into it in more detail yet. Say we have a few independent port pairs:

A -> B, C -> D, and E -> F

At least in cases where this has been verified, A and B are in different processes. C, D, E, and F are in A's process. D is passed over A to B, then F is immediately passed over C to D before D is actually transferred to B.

This ultimately leads to a few proxies being created to get E pointing to the right place. First:

E -> F -> G

with G still in A's process. F may send an ObserveProxy(F, G) to G now, and this will eventually get forwarded.

D will arrive in B's process as a new port, call it H. At this point the message carrying F (now G) will be forwarded to H, creating a new port J (in B's process) and proxying G to it. So we have:

E -> F -> G -> J

Now G will send an ObserveProxy(G, J) to J which will eventually forward to E.

The race happens between the ObserveProxy(F, G) and ObserveProxy(G, J) events. If the former arrives at E before the latter does, everything is fine. If not, this happens:

  1. E receives ObserveProxy(G, J) and forwards to F
  2. F receives ObserveProxy(G, J) and updates its peer (so now E -> F -> J)
  3. E finally receives the ObserveProxy(F, G) and updates its peer (so E -> G [OOPS...])

What's not yet clear to me is why they can arrive out of order, and whether this is a bug in the EDK messaging layer or a bug in Node::Impl.

FWIW this can be observed flakily in PipesTest.PassMoarMessagePipesCrossProcess. The test can hang waiting to read a message that will never arrive because of the race.

**Comment by darinf** [comment] 2015-12-28 16:20
I think this is a bug in ports.

**Comment by darinf** [comment] 2015-12-28 19:03
While exploring this issue, I found another possibly related issue: A transferred port can be exposed via MessagesAvailable before the referring message is delivered to the caller. This could be pretty confusing to the caller. Fixed with commit 79abfb256ff6aafad2d00a85e7e36d5b5fe6f51f.

**Comment by darinf** [comment] 2015-12-28 19:10
I can still repro the hang. Investigating...

**Comment by darinf** [comment] 2015-12-28 19:33
The issue is related to removing the proxy too soon. Probably we are not sending the correct "last_sequence_num" in the ObserveProxyAck event. I need to think on it more.

To work around this issue you can just add an early return in Node::Impl::ObserveProxyAck. That will prevent the proxy node from being removed.

**Comment by darinf** [comment] 2015-12-29 01:25
Temporary fix landed at commit 9231d308a1daf7d79888543abbbe41159dc8d045

**Comment by darinf** [comment] 2015-12-29 08:42
Proper fix here:
58793ea001da4e7ce5b3809b5df425b81db09653

This still needs a unit test.

**Comment by darinf** [comment] 2015-12-29 21:31
It turns out that last commit was insufficient. We also need to delay updating the peer pointer for a proxy pointing to a proxy. Better / real fix is at commit e4c8101915d960e844062acfacb634b1c70960a4

**Closed** 2015-12-29 22:15 UTC
